"""Update Product model with image_path and constraints

Revision ID: 144a4bd8a739
Revises: 
Create Date: 2024-12-11 16:36:59.076267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144a4bd8a739'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=100), nullable=False))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
